### ISSUE TITLE
Izris zemljevida

### ISSUE THREAD

**Issue by TjasaRen** [RenkoT97/APPR-2018-19#1]
Uporabila sem funkcijo uvozi.zemljevid:
europe <- uvozi.zemljevid("https://mapcruzin.com/download-shapefile/europe-natural-shape.zip",
                          "natural", encoding="Windows-1250")
Kako dobim sliko zemljevida iz dobljenega SpatialPolygonsDataFrama (na sliki)?

![screenshot 2019-01-05 20 48 37](https://user-images.githubusercontent.com/28481637/50728597-c0a85000-112c-11e9-931f-75f594bfae37.png)

**Comment by MarvinHerzog** [comment]
Na konec moraš dodati še `fortify()`

```
europe <- uvozi.zemljevid("https://mapcruzin.com/download-shapefile/europe-natural-shape.zip",
"natural", encoding="Windows-1250") %>% fortify()
```
Zemljevid, ki ga uporabljaš, je precej velik po velikosti datoteke. Morda razmisli o kakšni alternativi, npr.  https://github.com/DomenFlakusBosilj/APPR-2018-19/issues/2#issuecomment-451737006, saj se ti sicer lahko zgodi, da boš imela težave na nekaterih računalnikih.
Zgornja rešitev ti zmanjša velikost datoteke iz 500mb na 3mb.

Sliko dobiš z `geom_polygon`, nekako tako:
```
ggplot(europe, aes(x=long, y=lat, group=group)) +   
  geom_polygon() + 
  labs(title="Evropa - osnovna slika") +
  theme(legend.position="none")
```

**Comment by TjasaRen** [comment]
Najlepša hvala
