### ISSUE TITLE
Poročilo

### ISSUE THREAD

**Issue by jaanos** [RenkoT97/APPR-2018-19#3]
Tvoje poročilo se prevede, tako da bom dodal povezavo na repozitorij za zagovore. Bi pa opozoril, da ga prevajaj v HTML, ne v PDF - pri gumbu *Knit* klikni na puščico in izberi *Knit to HTML*. Ko boš znova prevajala, bo potem klik na *Knit* spet sprožil prevajanje v HTML.

Če želiš, da se ti grafi izrišejo, bo treba kodo postaviti v ustrezen blok, sicer se bo izpisala kot besedilo:
~~~R
```{r graf1, echo=FALSE, message=FALSE, warning=FALSE}
graf1
```
~~~
Parameter `warning=FALSE` lahko postaviš tudi pri uvozu (in po potrebi še drugod), da se ti opozorila ne bodo izpisovala v poročilo.

**Comment by jaanos** [comment]
Vidim, da si uredila opozorila in grafe, tako da sem posodobil povezavo. Vseeno pa uredi tudi prevajanje v HTML, da bo projekt deloval tudi na Binderju (zdaj je na voljo tudi knjižnica `eurostat`, tako da bi moralo delovati).

**Comment by TjasaRen** [comment]
Hvala. Poskusila sem urediti prevajanje v HTML, a nisem pripričana, ali je zdaj v redu.

**Comment by MarvinHerzog** [comment]
Poročilo se lepo prevede v HTML, edino še par malenkosti:
* Priporočam, da preimenuješ vse šumnike v imenih stolpcev/spremenljivk v različice brez strešic (Ž -> Z, ipd.), sicer se lahko zgodi, da na nekaterih sistemih koda ne bo delovala. Najlažje to narediš tako, da s CTRL + F uporabiš *find and replace* po vseh glavnih skriptah, razen po vizualizacija1.r, kjer lahko pustiš šumnike v *ggplot*-ovih tekstovnih elementih, kot so `ggtitle`, `xlab` ipd.
* Opažam, da velikokrat svoje skripte `source`-aš kar preko GitHub-a, npr.
```
source("https://raw.githubusercontent.com/RenkoT97/APPR-2018-19/master/uvoz/tabela4.r", encoding="UTF-8")
```
Ko delaš na projektu ga v splošem najprej *pull*-aš k sebi, kar pomeni, da imaš vse te skripte pri sebi lokalno.  Tako lahko kličeš vse datoteke kar relativno na glavno mapo projekta, npr.
```
source("uvoz/tabela4.r", encoding="UTF-8")
```
`source` na tak način deluje tudi na Binderju.
Edina izjema je morda `source("https://raw.githubusercontent.com/jaanos/APPR-2018-19/master/lib/uvozi.zemljevid.r")`, saj je Janoš nedavno posodobil svojo [skripto za uvoz zemljevidov](https://github.com/jaanos/APPR-2018-19/blob/master/lib/uvozi.zemljevid.r). To vrstico lahko pustiš kot je, ali pa kar v svojem projektu posodobiš skripto [*uvozi.zemljevid.R*](https://github.com/RenkoT97/APPR-2018-19/blob/master/lib/uvozi.zemljevid.r) v mapi *lib*, nato pa jo kličeš relativno, kot na primeru zgoraj.

**Comment by TjasaRen** [comment]
Hvala
