### ISSUE TITLE
Shiny

### ISSUE THREAD

**Issue by TjasaRen** [RenkoT97/APPR-2018-19#4]
Spoštovani,
Načeloma sem s projektom zaključila, a imam težavo pri poročilu; shiny ne dela hkrati z ostalimi grafi. Če ga zakomentiram, ostalo dela normalno, če pa ga pustim, se namesto slik ostalih grafov pojavijo prazna mesta z vprašaji. Ali Vas lahko prosim, da mi poveste, kaj je narobe? Hvala za Vaš čas.

**Comment by jaanos** [comment]
Pri meni deluje, tako da bom kar dodal povezavo na repozitorij za zagovore, z @alenFMF pa se lahko domeniš za termin zagovora. @MarvinHerzog, lahko prosim preveriš, ali se pri tebi pojavijo opisani problemi? Na Binderju še ne deluje, ker knjižnica `factoextra` še ni na voljo - bom za to še poskrbel.

Imam sicer še nekaj pripomb:
* Uvožene razpredelnice niso v obliki *tidy data*, saj imaš (razen pri `tabela2`) več stolpcev z isto lestvico. Za pretvorbo lahko uporabiš funkcijo `melt` iz knjižnice `reshape2`.
* Na prvem grafu ter pri nekaterih izbirah v Shinyju se na osi y pojavijo oznake v eksponentni notaciji. Da se ji izogneš, lahko podatke deliš npr. z 1000000 ter ustrezno označiš enoto v oznaki osi.
* Pri črtnih grafih zaradi velikega števila prikazanih držav ni mogoče enostavno razbrati, kateri barvni odtenek pripada kateri državi. Svetujem, da se omejiš samo na nekaj najbolj zanimivih držav.
* Podobno lahko narediš tudi pri tortnem diagramu, le da ostalih držav ne izpustiš, pač pa jih združiš kot *Ostale*.
* Graf, na katerem prikazuješ skupine, je nepregleden, saj se oznake prekrivajo. Poleg tega delaš razvrščanje po eni sami dimenziji. Svetujem, da raje razvrščaš države (brez leta) po vseh podatkih, ki jih imaš - vsak stolpec razpredelnice `podatki` naj torej ustreza kombinaciji leta in vidika deleža BDP (iz podatkov v obliki *tidy data* lahko tako obliko dobiš s funkcijo `dcast` iz knjižnice `reshape2`).
* Odsvetujem uvažanje knjižnice `plyr` (v `tabela4.r`), saj se utegnejo pojaviti težave s funkcijami iz knjižnice `dplyr`.
* Pri Shiny aplikaciji se pojavi drsnik, ker porabi preveč vertikalnega prostora - pri `shinyApp` dodaj parameter npr. `options=list(width="100%", height=1000)` ter ustrezno popravi vrednost pri `height`, da bo lepo izgledalo.

Mimogrede, svetujem, da programov iz mape `uvoz` ne kličeš na drugih mestih (`vizualizacija1.r`, `analiza.r`, `shiny.R`), saj jih že kličeš v poročilu in se zato deli uvoza izvedejo večkrat. Prav tako namesto klicanja `uvozi.zemljevid.r` iz vzorčnega repozitorija raje popravi lokalno različico - glej JernejcicZan#1.

**Comment by MarvinHerzog** [comment]
Pozdravljena, ravno sem preverjal zakaj se ne prevede na Binderju. Lokalno mi vse dela tako kot more. Morda je težava nekje v encodingu, glede na to da večina datotek `source` aš z *UTF-8* encoding, shiny pa z *WINDOWS-1252*. Poskusi se poigrati še z encoding nastavitvami v RStudio. Bom še jutri preveril, če se mi prevede na službenem računalniku.

**Comment by jaanos** [comment]
@RenkoT97, če imaš čas, se lahko oglasiš jutri ob 11h v kabnetu 5.14 s svojim računalnikom (sklepam, da se tam pojavi težava), pa bova pogledala. Prosim sporoči, če prideš.

**Comment by TjasaRen** [comment]
Bom prišla. Najlepša hvala.

**Comment by TjasaRen** [comment]
Spoštovani,
Popravila sem stvari, za katere se mi prej rekli. Ali mi lahko prosim posodobite povezavo, če je v redu?
Najlepša hvala

**Comment by jaanos** [comment]
Sem posodobil povezavo.

**Comment by TjasaRen** [comment]
Hvala
